import Head from 'next/head'
import Categories from '../components/Categories'
import PostCards from '../components/PostCards'
import PostWidget from '../components/PostWidgets'
import { getPosts, getSimilarPosts } from '../services/index'
import FeaturedPosts from '../section/featuredPost'

// const Posts = [
//   { title: 'testing react', excert: 'excert testing react js' },
//   { title: 'testing react', excert: 'excert testing react js' 

export default function Home({ posts }) {
  // console.log(posts)
  // let p3 = JSON.parse(JSON.stringify(posts[0].node));
  // console.log('p3' + p3)
  return (
    <div className='container mx-auto px-10 mb-0 '>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FeaturedPosts />
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-sapn-1'>
          {posts.map((post , index) => {
            return (
              <div key={index}>
                <PostCards  post={post.node} />
              </div>
            )
          })
          }
        </div>
        <div className='lg:col-span-4 col-span-1'>
          <div className='lg:sticky relative top-8'>
            <PostWidget />

            <Categories />
          </div>

        </div>

      </div>
    </div>
  )
}

// Fetch data at build time
export async function getStaticProps() {
  const posts = await getPosts();

  return {
    props: {
      posts,

    },
  };
}